 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

datasets:
  GO_protein_function: # name of the dataset builder
    dataset_card: dataset_card/protein_function.md
    # data_dir: ${env.data_dir}/datasets
    data_type: features # [images|videos|features]

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          url: https://storage.googleapis.com/GO_protein_function_train.csv
          #storage: /cluster/home/wenkai/LAVIS/data/pretrain/mf_bp_cc/swissprot_domain_seq_prompt_cc_new.csv
          #storage: /cluster/home/wenkai/LAVIS/data/pretrain/mf_bp_cc/train_exp_prompt_bp_new.csv
          #storage: /cluster/home/wenkai/LAVIS/data/pretrain/cases_bp.csv
          storage: /cluster/home/wenkai/LAVIS/data/pretrain/mf_bp_cc/cases_bp.csv
          #storage: /cluster/home/wenkai/LAVIS/data/pretrain/mol_instruction/test_union.pkl
          #storage: /cluster/home/wenkai/LAVIS/data/pretrain/deepgose/train_mf_go_exp.pkl
          #storage: /cluster/home/wenkai/LAVIS/data/pretrain/deepgose/train_cc_swissprot_domain.pkl
        val:
          url: https://storage.googleapis.com/GO_protein_function_val.csv
          #storage: /cluster/home/wenkai/LAVIS/data/review_func_time_split/val_mf.csv
          storage: /cluster/home/wenkai/LAVIS/data/pretrain/mf_bp_cc/test_exp_mf_new.csv
          #storage: /cluster/home/wenkai/LAVIS/data/pretrain/multitask/test_mf_go_exp.pkl
        test:
          url: https://storage.googleapis.com/GO_protein_function_test.csv
          #storage: /cluster/home/wenkai/LAVIS/data/pretrain/multitask/cases_mf.csv
          #storage: /cluster/home/wenkai/LAVIS/data/pretrain/cases_mf.csv
          #storage: /cluster/home/wenkai/LAVIS/data/pretrain/deepgose/test_mf_go_exp.pkl
          storage: /cluster/home/wenkai/LAVIS/data/pretrain/mf_bp_cc/test_exp_prompt_mf_new.csv
